# fly.toml file generated for huonggio on 2022-08-01T10:22:19+07:00

app = "huonggio"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_BASE_PATH_API="https://ken-shop-api.herokuapp.com/api/v1/"
    GOOGLE_ID="603048550655-67jqogc0812nabi73v2745t6ehrvk0am.apps.googleusercontent.com"
    GOOGLE_SECRET="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"
    JWT_SECRET="afeadf637e4527be3b277e8a9ca54d00"
    NEXT_PUBLIC_GOOGLE_ANALYTICS="G-JRK66KZS3X"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
